json.current_sparql_endpoints @nbSPARQLendpoints
json.max_num_sparql_endpoints @maxSPARQLendpoints

json.current_sparql_triples @nbSPARQLtriples
json.max_sparql_triples @maxSPARQLtriples

json.current_files @nbFilestores
json.max_num_files @maxFilestores

json.current_files_size @nbFilestoresSize
json.max_files_size @maxFilestoresSize

json.current_num_data_transformations @nbTransformations
json.max_num_data_transformations @maxTransformations
