json.current @nbDataDistributions
json.max_num_distributions @maxDataDistributions

json.current_num_data_pages @nbDataPages
json.maximum_num_data_pages @maxDataPages

json.current_num_data_transformations @nbTransformations
json.max_num_data_transformations @maxTransformations