development:
  publicPath: <%= ENV["GRAFTWERK_URI"] %>

test:
  publicPath: <%= ENV["GRAFTWERK_URI"] %>

production:
  publicPath: <%= ENV["GRAFTWERK_URI"] %>

staging:
  publicPath: <%= ENV["GRAFTWERK_URI"] %>
